spring.application.name=demo
#/WEB-INF/views/ 라는 경로의 jsp 파일을 인식
#아래설정을 추가해주지 않으면 기본 설정인 resources/static 경로로 찾아가게 됨
spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.static-path-pattern=/webapp/WEB-INF/views/
spring.mvc.view.suffix=.jsp

server.port=8080

# JSP 수정사항 반영
server.servlet.jsp.init-parameters.development=true